### ISSUE TITLE
Dataset Availability

### ISSUE THREAD

**Issue by pemo-ml** [weiliansong/FARSA#1]
Hello Weilian,

I noticed that this repository only includes one panaromic image for inference, but no access to the dataset used for training & evaluation.
Is the dataset you used with the annotations made by usRAP inspectors publicly available? If so, where can it be found?

Great work on the paper!

Thank you and kind regards,
Peter

**Comment by weiliansong** [comment]
Hi Peter!

Unfortunately we don't have the rights to release the dataset publicly. However, if you would like to email us with specifics about your application, we can discuss with our collaborators and potentially share the data with you. Please contact Dr. Nathan Jacobs at jacobs@cs.uky.edu for further discussions.

Thank you,
William
